config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  devise_for :advisers, controller:{
    sessions: 'advisers/sessions',
    passwords: 'advisers/passwords',
    registrations: 'advisers/registrations'
  }

  root to: "tops#index"

  resources :users, only: [:index, :edit, :update]
  resources :advisers, only: [:edit, :update]
  resources :item_selects, only: [:new, :create]
  resources :tops_items
  resources :rooms, only: [:new, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end
end

app/models/adviser.rb
class Adviser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :rooms
  has_one_attached :image
  has_many :tops_items, through: :item_selects
  has_many :item_selects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item_select.rb
class ItemSelect < ApplicationRecord
  has_many :tops_items
  has_many :advisers

  validates :tops_item_id, presence: true
  validates :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :adviser
  has_many :messages, dependent: :destroy
end

app/models/tops_item.rb
class TopsItem < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  validates :images, presence: true
  has_many :advisers, through: :item_selects
  has_many :item_selects
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  
  has_many :rooms
  has_one_attached :image
  has_one :tops_item
end

app/controllers/advisers_controller.rb
class AdvisersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(adviser_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def adviser_params
    params.require(:advisers).permit(:nickname, :email, :self_introduction, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    if resource_class == User
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    elsif resource_class == Adviser
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    else
      super
    end
  end
end

app/controllers/item_selects_controller.rb
class ItemSelectsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def new
    @selected_item = ItemSelect.new
    @user = User.find_by(id: params[:format])
  end 

  def create
    @selected_item = ItemSelect.new(select_params)
    if @selected_item.save!
      redirect_to root_path   
    else 
      redirect_to room_path     
    end
  end

  private
  def select_params
    params.permit(:tops_item_id, :adviser_id, :user_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if user_signed_in?
      @message.is_user = true
    elsif adviser_signed_in?
      @message.is_user = false
    end
    @message.room_id = @room.id
    if @message.save
      redirect_to room_path(@room)
    else
      redirect_to room_path(@room)
    end
  end

  private
  
  def message_params
    params.require(:message).permit(:content)
  end 
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end 

  def new 
    @room = Room.new
  end 

  def show
    @room = Room.find(params[:id]) 
    @message = Message.new 
    @messages = @room.messages
    @selected_item = ItemSelect.where(adviser_id: @room.adviser_id).where(user_id: @room.user_id).pluck(:tops_item_id)
    @tops_item = TopsItem.find_by(user_id: @room.user_id)
    if @selected_item.present?
      @image = @tops_item.images.find_by(blob_id: @selected_item)
    end
    if user_signed_in?
      if @room.user.id == current_user.id
        @adviser = @room.adviser
      else
        redirect_to "/"
      end
    elsif adviser_signed_in?
      if @room.adviser.id == current_adviser.id
        @user = @room.user
      else
        redirect_to "/"
      end
    else
      redirect_to "/"
    end
  end

  def create
    if user_signed_in?
      @room = Room.new(room_adviser_params)
      @room.user_id = current_user.id
    elsif adviser_signed_in?
      @room = Room.new(room_user_params)
      @room.adviser_id = current_adviser.id
    else
      redirect_to "/"
    end

    if @room.save
      redirect_to :action => "show", :id => @room.id
    else
      redirect_to "/"
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  private
  def room_adviser_params
    params.require(:room).permit(:adviser_id)
  end

  def room_user_params
    params.require(:room).permit(:user_id)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    if user_signed_in?
      @advisers = Adviser.all
      rooms = current_user.rooms
      @adviser_ids = []
      rooms.each do |r|
        @adviser_ids << r.adviser_id
      end 
    elsif adviser_signed_in?
      @users = User.all
      rooms = current_adviser.rooms
      @user_ids = []
      rooms.each do |r|
        @user_ids << r.user_id
      end
    end
  end
end

app/controllers/tops_items_controller.rb
class TopsItemsController < ApplicationController
  def new
    @tops_item = TopsItem.new
  end
  def create
    @tops_item = TopsItem.new(tops_params)
    if @tops_item.save
      redirect_to root_path
    else 
      render :new
    end 
  end

  private
  def tops_params
    params.require(:tops_item).permit({images: []}).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @tops_item = TopsItem.all
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @item = @user.item
  end

  private

  def user_params
    params.require(:users).permit(:nickname, :email, :image)
  end
end

app/helpers/advisers_helper.rb
module AdvisersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_selects_helper.rb
module ItemSelectsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tops_items_helper.rb
module TopsItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/item_selects/new.html.erb
<%= form_with url: item_selects_path, id: 'new_post', local: true do |f| %>
  <div style="display: flex; flex-wrap: wrap; width: 750px;">
    <% @user.tops_item.images.each do |image| %>
      <div style="display: flex; margin:5px 5px 5px 0;" class="image-field">
        <%= f.check_box :tops_item_id, { multiple: false }, image.id, false %>
          <label for="tops_item_id_<%= image.id %>">
            <%= image_tag image, size: '50*50'%>
          </label>
      </div>
    <% end %>
    <%= f.hidden_field :adviser_id, value: current_adviser.id %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <div class="submit-btn">
      <%= f.submit '送信' %>
    </div>
  </div>
<% end %>

app/views/messages/_main_caht.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <% if users_signed_in? %>
        <%= link_to room.advisers.nickname, room_messages_path(room)%>
      <% elsif advisers_signed_in? %>
        <%= link_to room.users.nickname, room_messages_path(room)%>
      <% end %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <% if users_signed_in? %>
        <%= message.users.nickname %>
      <% elsif advisers_signed_in? %>
        <%= message.advisers.nickname %>
      <% end %>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <% if user_signed_in? %>
      <%= link_to current_user.nickname, edit_user_registration_path(current_user) %>
    <% elsif adviser_signed_in? %>
      <%= link_to current_adviser.nickname, edit_adviser_registration_path(current_user) %>
    <% end %>
  </div>
  <div class="create-room">
    <a href="#">チャットを作成する</a>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <% if user_signed_in? %>
          <%= link_to room.adviser.nickname, room_messages_path(room)%>
        <% elsif adviser_signed_in? %>
          <%= link_to room.user.nickname, room_messages_path(room)%>
        <% end %>
      </div>
    </div>
  <% end %>  
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<h1>チャットサンプル</h1>
<% if user_signed_in? %>
  <h3><%= @adviser.nickname %>とのチャットルーム</h3>
  <div class="chat-field">
    <% @messages.each do |m| %>
      <!-- メッセージがUserによるものだったら -->
      <% if m.is_user %>
        <!-- メッセージを右に寄せる -->
        <div class="right-message">
          <%= m.content %>
        </div>
      <!-- メッセージがadviserによるものだったら -->
      <% else %>
        <!-- メッセージを左に寄せる -->
        <div class="left-message">
          <%= m.content %>
        </div>
      <% end %>
    <% end %>
  </div>
  <% elsif adviser_signed_in?%>
  <h3><%= @user.nickname %>とのチャットルーム</h3>
  <div class="chat-field">
    <% @messages.each do |m| %>
      <!-- メッセージがUserによるものだったら -->
      <% if m.is_user %>
        <!-- メッセージを左に寄せる -->
        <div class="left-message">
          <%= m.content %>
        </div>
      <!-- メッセージがadviserによるものだったら -->
      <% else %>
        <!-- メッセージを右に寄せる -->
        <div class="right-message">
          <%= m.content %>
        </div>
      <% end %>
    <% end %>
    <% if @selected_item.present? %>
        <%= image_tag @image %>
    <% end %>
  </div>
<% end %>
<%= link_to '服装選択へ', new_item_select_path(@room.user_id)%>
<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content %>
    <label class="form-image">
    
  <%= f.submit "メッセージを送る"%>
<% end %>

app/views/tops_items/new.html.erb
<%= form_with model: @tops_item, id: 'new_post', local: true do |f| %>
  <div class="image-field">
    <div id="previews"></div>
    <div class="click-upload">
      <%= f.file_field :images, name: 'tops_item[images][]', data: {index: 0} %>
    </div>
  </div>
  <div class="submit-btn">
    <%= f.submit '送信' %>
  </div>
<% end %>